version: 2.1
orbs:
  # "cypress-io/cypress@1" installs the latest published
  # version "1.x.y" of the orb. We recommend you then use
  # the strict explicit version "cypress-io/cypress@1.x.y"
  # to lock the version and prevent unexpected CI changes
  cypress: cypress-io/cypress@1.19.1
workflows:
  build-and-test:
    jobs:
      - cypress/run:
          executor: cypress/browsers-chrome77
          spec: cypress/integration/samples/AngularForm.js
          record: false
          browser: chrome
          filters: 
            branches:
              only:
                - master
                - test
              ignore:
                - circleci-project-setup
          store_artifacts: true
          post-steps:
            - store_artifacts:
                path: mochawesome-report